packages:
    - ./client
    - ./server

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@jderstd/express"
    - "@jderstd/hono"
    - "@jderstd/hono-openapi"
